# mkdocs.yml
# This file is configured only for generating markdown files, not for building a site.

# We'll put the generated markdown in a temporary directory.
site_name: temp_markdown_output
docs_dir: temp_markdown_output

# Enable the necessary plugins
plugins:
  - gen-files:
      scripts:
        # This points to the script that will create markdown files from your python files
        - open_ticket_ai/scripts/doc_generation/generate_docs.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # We recommend these settings for clean markdown output
            show_root_heading: true
            show_source: false # Set to true if you want to include source code blocks
            heading_level: 2
