```plantuml
@startuml
allow_mixing

node OTOBO {
  node API
  node DB
}

node ATCIntegration {
  interface TicketAdapter {
    + fetchTickets(queueName)
    + updateTicketQueue(ticketId, newQueue)
  }
  class AdapterFactory {
    + getAdapter(systemType, config)
  }

  class OTOBOAdapter{
  }
  class ZnunyAdapter{
  }
  class FreshdeskAdapter{
  }
  AdapterFactory --> TicketAdapter
}

node ATC {
  node AIRunner
  class AITrainer {
    + trainModel()
  }

  class AIClassifier {
    + classifyTicket(ticket)
  }
  node AIModel
}

ATCIntegration.OTOBOAdapter --> OTOBO.API : REST

ATC.AIRunner --> ATC.AITrainer : trainModel()
ATC.AITrainer --> AIModel : storeModel()
ATC.AIRunner --> AIClassifier : classifyTicket()
ATC.AIClassifier --> ATC.AIModel : useModel()
AIClassifier --> ATCIntegration.TicketAdapter : updateTicketQueue()
@enduml
```
