```plantuml
@startuml
allow_mixing

node OTOBO {
  node API
  node DB
}

node ATCIntegration {
  interface TicketAdapter {
    + fetchTickets(queueName)
    + updateTicketQueue(ticketId, newQueue)
  }
  class AdapterFactory {
    + getAdapter(systemType, config)
  }
  class IntegrationBridge {
    - adapter: TicketAdapter
    + processTickets()
  }

  AdapterFactory --> TicketAdapter
  IntegrationBridge --> TicketAdapter
}

node ATC {
  node RESTAPI
  node AIRunner
  class DataCollector {
    + collectTickets()
  }
  class AITrainer {
    + trainModel()
  }
  node AIModel
}

ATCIntegration --> OTOBO.API : REST
ATCIntegration --> ATC.RESTAPI : REST

ATC.RESTAPI --> ATC.AIRunner : runClassification()
ATC.AIRunner --> DataCollector : collectTickets()
DataCollector --> ATCIntegration.IntegrationBridge : fetchTickets()
ATC.AIRunner --> ATC.AITrainer : trainModel()
ATC.AITrainer --> ATCModel : storeModel()

@enduml
```
