run_config:
  hf_token: "your_huggingface_token_here"

  ticket_classifiers:
    queue_classification:
      tokenizer: "ticket_combined_email_tokenizer"
      hf_model: "google/flan-t5-base"
      ticket_attribute: "queue_id"
      confidence_threshold: 0.5
      low_confidence_value: "misc"
      ticket_to_model_results_map:
        - otobo_queue1:
            - "IT & Technology/Security Operations"
        - otobo_queue2:
            - "IT & Technology/Software Development"
        - research_development:
            - "Science/*"
        - misc:
            - "*"
    priority_classification:
      tokenizer: "ticket_combined_email_tokenizer"
      hf_model: "google/flan-t5-base"
      ticket_attribute: "priority"
      ticket_to_model_results_map:
        - 1:
            - 1
        - 2:
            - 2
        - 3:
            - 3
        - 4:
            - 4
        - 5:
            - 5
  ticket_system_adapter:
    system_name: "otobo"
    rest_settings:
      base_url: "https://your-otobo-instance.com"
      username: "your_username"
      password: "your_password"
      search_url: "/api/v1/ticket/search"
      get_url: "/api/v1/ticket/get"
      update_url: "/api/v1/ticket/update"
    incoming_queue: "otobo_queue1"